# json_value_tester
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module JsonValueTester
  # Http response received.
  class HttpResponse < CoreLibrary::HttpResponse
  end
end
