# json_value_tester
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module JsonValueTester
  # Content-Type.
  class ContentType
    CONTENT_TYPE = [
      # TODO: Write general description for ENUM_APPLICATIONXWWWFORMURLENCODED
      ENUM_APPLICATIONXWWWFORMURLENCODED = 'application/x-www-form-urlencoded'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      CONTENT_TYPE.include?(value)
    end
  end
end
